<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="B_Skierowania" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="B_Skierowania">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="B_Faktura_ID" index-key="B_Faktura_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="B_Firma_ID" index-key="B_Firma_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="B_Pacjent_ID" index-key="B_Pacjent_ID " primary="no" unique="no" clustered="no" order="asc"/>
<od:index index-name="PrimaryKey" index-key="B_ID " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:index index-name="Sanepid" index-key="B_książeczka " primary="no" unique="no" clustered="no" order="asc"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAARKs/WNfCjQJgZsagN+fH3AAAAAOR2aYiviOZAAAAAAAAAAABCAF8A
UwBrAGkAZQByAG8AdwBhAG4AaQBhAAAAAAAAAIXWA8OLkDJIhJ2f0C4CxJIHAAAA
ESrP1jXwo0CYGbGoDfnx90IAXwBJAEQAAAAAAAAAPxw7bMWbMkyupA0lBJRLtQcA
AAARKs/WNfCjQJgZsagN+fH3QgBfAFAAYQBjAGoAZQBuAHQAXwBJAEQAAAAAAAAA
c+8F2Ir5sEyJStYiTma3QAcAAAARKs/WNfCjQJgZsagN+fH3QgBfAEIAYQBkAGEA
bgBpAGUAXwBJAEQAAAAAAAAAWQipiKfPAEqZYBU/61MfgwcAAAARKs/WNfCjQJgZ
sagN+fH3QgBfAEYAaQByAG0AYQBfAEkARAAAAAAAAADXktLN1KAKR704gusHMZbf
BwAAABEqz9Y18KNAmBmxqA358fdCAF8ARABhAHQAYQBTAGsAaQBlAHIAbwB3AGEA
bgBpAGEAAAAAAAAAE5YConXFAEaLmGiLZ6mbcgcAAAARKs/WNfCjQJgZsagN+fH3
QgBfAEkARABfAE8ATABEAAAAAAAAAAK4d2qc4kpMjXSmK6hToHIHAAAAESrP1jXw
o0CYGbGoDfnx90IAXwBJAEQAXwBwAGEAYwBqAGUAbgB0AGEAAAAAAAAA4hf2//st
8kyxANF+PkhYUgcAAAARKs/WNfCjQJgZsagN+fH3QgBfAEYAYQBrAHQAdQByAGEA
XwBJAEQAAAAAAAAAgrFK8xyKMU26YmcSkgExTQcAAAARKs/WNfCjQJgZsagN+fH3
QgBfAFQAeQBwAEIAYQBkAGEAbgBpAGEAAAAAAAAAAi2mSzuqTECdRti4x+XKeAcA
AAARKs/WNfCjQJgZsagN+fH3QgBfAFMAdABhAG4AbwB3AGkAcwBrAG8AAAAAAAAA
8Kjni5p6xUKCDPDH4wvJMQcAAAARKs/WNfCjQJgZsagN+fH3QgBfAFIAZQBnAGkA
cwB0AHIAYQB0AGkAbwBuAEQAYQB0AGUAAAAAAAAAZ859PRW2qEuPzQVhV6cwzAcA
AAARKs/WNfCjQJgZsagN+fH3QgBfAGMAegB5AG4AbgBpAGsAXwBmAGkAegB5AGMA
egBuAHkAAAAAAAAAm/s93G/8TUiHTsGli4z0DwcAAAARKs/WNfCjQJgZsagN+fH3
QgBfAGMAegB5AG4AbgBpAGsAXwBmAGkAegB5AGMAegBuAHkAXwBvAHAAaQBzAAAA
AAAAANfvAe+pwd5DoSdx7RqQJ8YHAAAAESrP1jXwo0CYGbGoDfnx90IAXwBjAHoA
eQBuAG4AaQBrAF8AcAB5AEIBbwB3AHkAAAAAAAAAb18xT9ScCUq6bPdvANrZpAcA
AAARKs/WNfCjQJgZsagN+fH3QgBfAGMAegB5AG4AbgBpAGsAXwBwAHkAQgFvAHcA
eQBfAG8AcABpAHMAAAAAAAAAHScaI08D5UCHvb/7nW1DvwcAAAARKs/WNfCjQJgZ
sagN+fH3QgBfAGMAegB5AG4AbgBpAGsAXwBjAGgAZQBtAGkAYwB6AG4AeQAAAAAA
AABZ60fdDERQRpTv34OGtmkvBwAAABEqz9Y18KNAmBmxqA358fdCAF8AYwB6AHkA
bgBuAGkAawBfAGMAaABlAG0AaQBjAHoAbgB5AF8AbwBwAGkAcwAAAAAAAAAjjKKq
6irLRIwBD+5Twcy8BwAAABEqz9Y18KNAmBmxqA358fdCAF8AYwB6AHkAbgBuAGkA
awBfAGIAaQBvAGwAbwBnAGkAYwB6AG4AeQAAAAAAAAAvBK/MjU1AT6dIDAiZlfM6
BwAAABEqz9Y18KNAmBmxqA358fdCAF8AYwB6AHkAbgBuAGkAawBfAGIAaQBvAGwA
bwBnAGkAYwB6AG4AeQBfAG8AcABpAHMAAAAAAAAA/IxnEARXgUmSn9EpHQ4HmQcA
AAARKs/WNfCjQJgZsagN+fH3QgBfAGMAegB5AG4AbgBpAGsAXwBpAG4AbgB5AAAA
AAAAAI2llNZDmqVJm8nfYaIwYR8HAAAAESrP1jXwo0CYGbGoDfnx90IAXwBjAHoA
eQBuAG4AaQBrAF8AaQBuAG4AeQBfAG8AcABpAHMAAAAAAAAA1FzfP+l3+k6N9zyz
VDHBEQcAAAARKs/WNfCjQJgZsagN+fH3QgBfAGMAegB5AG4AbgBpAGsAXwBzAGEA
bgBlAHAAaQBkAAAAAAAAABnIxQZcmQJNgNfUEGjwv2QHAAAAESrP1jXwo0CYGbGo
Dfnx90IAXwBjAHoAeQBuAG4AaQBrAF8AcwBhAG4AZQBwAGkAZABfAG8AcABpAHMA
AAAAAAAAbi6uI4dn+UClumSAKFfv8AcAAAARKs/WNfCjQJgZsagN+fH3QgBfAEMA
bwBtAG0AZQBuAHQAcwAAAAAAAADVf7a5I/hESLlMz/LQx2wbBwAAABEqz9Y18KNA
mBmxqA358fdCAF8AUwBjAGEAbgAAAAAAAADG51DsBTxjSaQ8j84sdhlpBwAAABEq
z9Y18KNAmBmxqA358fdCAF8AWgBhAHMAdwBpAGEAZABjAHoAZQBuAGkAZQAAAAAA
AAAPj4TqmfedQYL0ABEkyX/sBwAAABEqz9Y18KNAmBmxqA358fdCAF8AawBzAGkA
BQF8AWUAYwB6AGsAYQAAAAAAAABhDeMz6fuIT7Y9c1MvCdK3BwAAABEqz9Y18KNA
mBmxqA358fdCAF8AQQBuAGsAaQBlAHQAYQAAAAAAAADXUkloJ/rzQ59T76TuDvi7
BwAAABEqz9Y18KNAmBmxqA358fdCAF8AQgBhAGQAAAAAAAAAijOn1SeBMEqI5j7y
pQe5YQcAAAARKs/WNfCjQJgZsagN+fH3QgBfAE4AbwB3AGUAAAAAAAAAnMYA7rf/
CE6+Ugb2vHUPtQcAAAARKs/WNfCjQJgZsagN+fH3QgBfAGsAYQByAHQAYQAAAAAA
AADYmG7Y+U97RoOYRelCSYXqBwAAABEqz9Y18KNAmBmxqA358fdCAF8AcgBlAGoA
ZQBzAHQAcgAAAAAAAAA8WkTstsbxRp4nEyEFrHbnBwAAABEqz9Y18KNAmBmxqA35
8fdCAF8AQQBjAHQAaQB2AAAAAAAAAJbWL2c2qQRHtJYCST2dhNwHAAAAESrP1jXw
o0CYGbGoDfnx90IAXwBXAHkAYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADAAAAAUA
AAAAAAAAAAAAAAAAAAAAAA==
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="RowHeight" type="3" value="288"/>
<od:tableProperty name="GUID" type="9" value="ESrP1jXwo0CYGbGoDfnx9w==
"/>
<od:tableProperty name="Filter" type="12" value="([B_Skierowania].[B_ID]=3377)"/>
<od:tableProperty name="OrderBy" type="12" value="[B_Skierowania].[B_ID], [B_Skierowania].[B_Pacjent_ID] DESC, [B_Skierowania].[B_Badanie_ID], [B_Skierowania].[B_Firma_ID], [B_Skierowania].[B_DataSkierowania] DESC"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="B_ID" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="hdYDw4uQMkiEnZ/QLgLEkg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Pacjent_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1944"/>
<od:fieldProperty name="ColumnOrder" type="3" value="2"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Pxw7bMWbMkyupA0lBJRLtQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_ID_OLD" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1884"/>
<od:fieldProperty name="ColumnOrder" type="3" value="3"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="E5YConXFAEaLmGiLZ6mbcg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_ID_pacjenta" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2628"/>
<od:fieldProperty name="ColumnOrder" type="3" value="5"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Arh3apziSkyNdKYrqFOgcg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Firma_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2136"/>
<od:fieldProperty name="ColumnOrder" type="3" value="6"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="WQipiKfPAEqZYBU/61Mfgw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Badanie_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2232"/>
<od:fieldProperty name="ColumnOrder" type="3" value="7"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="c+8F2Ir5sEyJStYiTma3QA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Faktura_ID" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2568"/>
<od:fieldProperty name="ColumnOrder" type="3" value="8"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="4hf2//st8kyxANF+PkhYUg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_DataSkierowania" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2928"/>
<od:fieldProperty name="ColumnOrder" type="3" value="9"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="data skierowania"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="15LSzdSgCke9OILrBzGW3w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_TypBadania" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2064"/>
<od:fieldProperty name="ColumnOrder" type="3" value="10"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="grFK8xyKMU26YmcSkgExTQ==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_Stanowisko" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3372"/>
<od:fieldProperty name="ColumnOrder" type="3" value="11"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Ai2mSzuqTECdRti4x+XKeA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_RegistrationDate" minOccurs="0" od:jetType="datetime" od:sqlSType="datetime" type="xsd:dateTime">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2604"/>
<od:fieldProperty name="ColumnOrder" type="3" value="12"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ShowDatePicker" type="3" value="1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="data badania"/>
<od:fieldProperty name="GUID" type="9" value="8Kjni5p6xUKCDPDH4wvJMQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_fizyczny" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="13"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="Z859PRW2qEuPzQVhV6cwzA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_fizyczny_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="14"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value=" // Czynniki szkodliwe"/>
<od:fieldProperty name="GUID" type="9" value="m/s93G/8TUiHTsGli4z0Dw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_czynnik_pyłowy" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="15"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1+8B76nB3kOhJ3HtGpAnxg==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_pyłowy_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="3720"/>
<od:fieldProperty name="ColumnOrder" type="3" value="16"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="b18xT9ScCUq6bPdvANrZpA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_czynnik_chemiczny" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1992"/>
<od:fieldProperty name="ColumnOrder" type="3" value="17"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="HScaI08D5UCHvb/7nW1Dvw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_chemiczny_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2460"/>
<od:fieldProperty name="ColumnOrder" type="3" value="18"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="WetH3QxEUEaU79+DhrZpLw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_czynnik_biologiczny" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="19"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="I4yiquoqy0SMAQ/uU8HMvA==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_biologiczny_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1956"/>
<od:fieldProperty name="ColumnOrder" type="3" value="20"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="LwSvzI1NQE+nSAwImZXzOg==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_czynnik_inny" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="2088"/>
<od:fieldProperty name="ColumnOrder" type="3" value="21"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="/IxnEARXgUmSn9EpHQ4HmQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_inny_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="22"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="jaWU1kOapUmbyd9hojBhHw==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_czynnik_sanepid" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="23"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="1FzfP+l3+k6N9zyzVDHBEQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_czynnik_sanepid_opis" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="24"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="GcjFBlyZAk2A19QQaPC/ZA==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_Comments" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1656"/>
<od:fieldProperty name="ColumnOrder" type="3" value="25"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="bi6uI4dn+UClumSAKFfv8A==
"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="B_Scan" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="26"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="dokument scan"/>
<od:fieldProperty name="GUID" type="9" value="1X+2uSP4REi5TM/y0MdsGw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Zaswiadczenie" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="27"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="Zaswiadczenie"/>
<od:fieldProperty name="GUID" type="9" value="xudQ7AU8Y0mkPI/OLHYZaQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_książeczka" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="28"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="dodatkowo ksiązećzka"/>
<od:fieldProperty name="GUID" type="9" value="D4+E6pn3nUGC9AARJMl/7A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Ankieta" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="29"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Description" type="10" value="Ankitata Nauczyciel"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="YQ3jM+n7iE+2PXNTLwnStw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Bad" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="30"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="było badanie"/>
<od:fieldProperty name="GUID" type="9" value="11JJaCf680OfU++k7g74uw==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Nowe" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1200"/>
<od:fieldProperty name="ColumnOrder" type="3" value="31"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="nowe"/>
<od:fieldProperty name="GUID" type="9" value="ijOn1SeBMEqI5j7ypQe5YQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_karta" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1272"/>
<od:fieldProperty name="ColumnOrder" type="3" value="32"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="karta wydrukowana"/>
<od:fieldProperty name="GUID" type="9" value="nMYA7rf/CE6+Ugb2vHUPtQ==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_rejestr" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="33"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="Description" type="10" value="jest data rejestracji"/>
<od:fieldProperty name="GUID" type="9" value="2Jhu2PlPe0aDmEXpQkmF6g==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Activ" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="1224"/>
<od:fieldProperty name="ColumnOrder" type="3" value="4"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="PFpE7LbG8UaeJxMhBax25w==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="B_Wyb" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="GUID" type="9" value="ltYvZzapBEe0lgJJPZ2E3A==
"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
