<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:od="urn:schemas-microsoft-com:officedata">
<xsd:element name="dataroot">
<xsd:complexType>
<xsd:sequence>
<xsd:element ref="BAD_Cennik" minOccurs="0" maxOccurs="unbounded"/>
</xsd:sequence>
<xsd:attribute name="generated" type="xsd:dateTime"/>
</xsd:complexType>
</xsd:element>
<xsd:element name="BAD_Cennik">
<xsd:annotation>
<xsd:appinfo>
<od:index index-name="PrimaryKey" index-key="Identyfikator " primary="yes" unique="yes" clustered="no" order="asc"/>
<od:tableProperty name="GUID" type="9" value="AhUpKvVjIkajyFv32Mgx3A==
"/>
<od:tableProperty name="Orientation" type="2" value="0"/>
<od:tableProperty name="OrderByOn" type="1" value="1"/>
<od:tableProperty name="NameMap" type="11" value="CswOVQAAAAACFSkq9WMiRqPIW/fYyDHcAAAAAPFjzK14ZeZAAAAAAAAAAABCAEEA
RABfAEMAZQBuAG4AaQBrAAAAAAAAAJDjrNOc0o5Fg6gAbvhTVykHAAAAAhUpKvVj
IkajyFv32Mgx3GIAXwBDAGUAbgBuAGkAawAAAAAAAACHrDFezZ6OQ4uJ5us7OWae
BwAAAAIVKSr1YyJGo8hb99jIMdxiAF8ATgBhAHoAdwBhAAAAAAAAABNI6EDflrxE
luTCM2kgzqYHAAAAAhUpKvVjIkajyFv32Mgx3EkAZABlAG4AdAB5AGYAaQBrAGEA
dABvAHIAAAAAAAAAHaHagfvgoEycuhw5aBNjxgAAAABX8GUeHWXmQAAAAAAAAAAA
QgBBAEQAXwBMAGkAcwB0AGEAAAAAAAAAw75gGXkepUK4XPRHBmwXKAcAAAAdodqB
++CgTJy6HDloE2PGYgBuAF8AbgBhAHoAdwBhAAAAAAAAAEfi7poEguJKsJmMR3tX
bzsHAAAAAhUpKvVjIkajyFv32Mgx3GIAXwBDAGUAbgBhAAAAAAAAABhh7VtMgkFN
smDTDIwn8H4HAAAAAhUpKvVjIkajyFv32Mgx3GIAXwBWAGEAdAAAAAAAAADpRS6p
u2WWQqMG2+Gr/w3VBwAAAB2h2oH74KBMnLocOWgTY8ZiAG4AXwBjAGUAbgBuAGkA
awAAAAAAAAB03Mja1bmHQ79/T0vl1O2MBwAAAAIVKSr1YyJGo8hb99jIMdxiAF8A
YQBjAHQAaQB2AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMAAAABQAAAAAAAAAAAAAA
AAAAAAAA
"/>
<od:tableProperty name="DefaultView" type="2" value="2"/>
<od:tableProperty name="DisplayViewsOnSharePointSite" type="2" value="1"/>
<od:tableProperty name="TotalsRow" type="1" value="0"/>
<od:tableProperty name="FilterOnLoad" type="1" value="0"/>
<od:tableProperty name="OrderByOnLoad" type="1" value="1"/>
<od:tableProperty name="HideNewField" type="1" value="0"/>
<od:tableProperty name="BackTint" type="6" value="100"/>
<od:tableProperty name="BackShade" type="6" value="100"/>
<od:tableProperty name="ThemeFontIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackThemeColorIndex" type="4" value="1"/>
<od:tableProperty name="AlternateBackTint" type="6" value="100"/>
<od:tableProperty name="AlternateBackShade" type="6" value="95"/>
<od:tableProperty name="ReadOnlyWhenDisconnected" type="1" value="0"/>
<od:tableProperty name="DatasheetGridlinesThemeColorIndex" type="4" value="3"/>
<od:tableProperty name="DatasheetForeThemeColorIndex" type="4" value="0"/>
<od:tableProperty name="PublishToWeb" type="2" value="1"/>
<od:tableProperty name="Filter" type="12" value="([BAD_Cennik].[b_Cennik]=&quot;PRM&quot;)"/>
<od:tableProperty name="OrderBy" type="12" value="[BAD_Cennik].[b_Nazwa], [BAD_Cennik].[b_Cennik]"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:complexType>
<xsd:sequence>
<xsd:element name="Identyfikator" minOccurs="1" od:jetType="autonumber" od:sqlSType="int" od:autoUnique="yes" od:nonNullable="yes" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="E0joQN+WvESW5MIzaSDOpg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="1"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="b_Nazwa" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="h6wxXs2ejkOLiebrOzlmng==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="3444"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT BAD_Lista.bn_nazwa FROM BAD_Lista; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="1"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="b_Cena" minOccurs="0" od:jetType="currency" od:sqlSType="money" type="xsd:double">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="R+LumgSC4kqwmYxHe1dvOw==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="#,##0.00&quot; zł&quot;;-#,##0.00&quot; zł&quot;"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="1045"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="b_Vat" minOccurs="0" od:jetType="longinteger" od:sqlSType="int" type="xsd:int">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="GGHtW0yCQU2yYNMMjCfwfg==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="DecimalPlaces" type="2" value="255"/>
<od:fieldProperty name="DefaultValue" type="12" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="DisplayControl" type="3" value="109"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
<xsd:element name="b_Cennik" minOccurs="0" od:jetType="text" od:sqlSType="nvarchar">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="kOOs05zSjkWDqABu+FNXKQ==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="2088"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Required" type="1" value="0"/>
<od:fieldProperty name="AllowZeroLength" type="1" value="1"/>
<od:fieldProperty name="DisplayControl" type="3" value="110"/>
<od:fieldProperty name="IMEMode" type="2" value="0"/>
<od:fieldProperty name="IMESentenceMode" type="2" value="3"/>
<od:fieldProperty name="UnicodeCompression" type="1" value="1"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
<od:fieldProperty name="RowSourceType" type="10" value="Table/Query"/>
<od:fieldProperty name="RowSource" type="12" value="SELECT BAD_Lista.bn_cennik FROM BAD_Lista; "/>
<od:fieldProperty name="BoundColumn" type="3" value="1"/>
<od:fieldProperty name="ColumnCount" type="3" value="1"/>
<od:fieldProperty name="ColumnHeads" type="1" value="0"/>
<od:fieldProperty name="AllowMultipleValues" type="1" value="0"/>
<od:fieldProperty name="AllowValueListEdits" type="1" value="0"/>
<od:fieldProperty name="ShowOnlyRowSourceValues" type="1" value="0"/>
</xsd:appinfo>
</xsd:annotation>
<xsd:simpleType>
<xsd:restriction base="xsd:string">
<xsd:maxLength value="255"/>
</xsd:restriction>
</xsd:simpleType>
</xsd:element>
<xsd:element name="b_activ" minOccurs="1" od:jetType="yesno" od:sqlSType="bit" od:nonNullable="yes" type="xsd:boolean">
<xsd:annotation>
<xsd:appinfo>
<od:fieldProperty name="GUID" type="9" value="dNzI2tW5h0O/f09L5dTtjA==
"/>
<od:fieldProperty name="ColumnWidth" type="3" value="-1"/>
<od:fieldProperty name="ColumnOrder" type="3" value="0"/>
<od:fieldProperty name="ColumnHidden" type="1" value="0"/>
<od:fieldProperty name="Format" type="10" value="Yes/No"/>
<od:fieldProperty name="DefaultValue" type="12" value="No"/>
<od:fieldProperty name="DisplayControl" type="3" value="106"/>
<od:fieldProperty name="TextAlign" type="2" value="0"/>
<od:fieldProperty name="AggregateType" type="4" value="-1"/>
<od:fieldProperty name="ResultType" type="2" value="0"/>
<od:fieldProperty name="CurrencyLCID" type="4" value="0"/>
</xsd:appinfo>
</xsd:annotation>
</xsd:element>
</xsd:sequence>
</xsd:complexType>
</xsd:element>
</xsd:schema>
